---
version: '3.7'

services:
  irc:
    image: pounce:latest
    container_name: irc
    restart: unless-stopped
    build:
      context: ./pounce
      dockerfile: Dockerfile
    ports:
      - '4333:4333'
    volumes:
      - ./pounce/logs:/logs
      - ./pounce/config:/config
    networks:
      web-stack:
        aliases:
          - "irc.local"

networks:
  web-stack:
    driver: 'bridge'
